version: "3.8"

services:
  postgres:
    image: postgres:17.4
    container_name: lendly_database
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lendly
    ports:
      - "5432:5432"
    volumes:
      - lendly_data:/var/lib/postgresql/data

volumes:
  lendly_data:
